name: New Internship
description: Contribute an internship to our list
title: 'New Internship'
labels: ['new_internship']
body:
  - type: markdown
    attributes:
      value: |
        ## New Internship Contribution Form
        Thanks for taking the time to contribute!
        > Make sure you've read `CONTRIBUTING.md` before submitting your internship
  - type: input
    id: url
    attributes:
      label: Link to Internship Posting
      placeholder: ex. example.com/link/to/posting
    validations:
      required: true
  - type: input
    id: company_name
    attributes:
      label: Company Name
      placeholder: ex. Google
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Internship Title
      placeholder: ex. ML Software Intern
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: |
        Where is the internship located? 
        Please separate locations with a pipe "|" if there are multiple options. 
        Include Remote if remote option available.
      placeholder: Singapore, Singapore | Kowloon, Hong Kong | Remote
    validations:
      required: true
  - type: input
    id: deadline
    attributes:
      label: Application Deadline
      description: |
        When is the Application Deadline? 
        Please separate deadline with a pipe "|" if there are multiple deadline/rounds. 
        Leave black if unknown.
      placeholder: September, 1 | June, 1
    validations:
      required: false
  - type: dropdown
    id: terms
    attributes:
      label: What term(s) is this internship offered for?
      multiple: true
      options:
        - Fall 2023
        - Winter 2024
        - Spring 2024
        - Summer 2024
        - Fall 2024
    validations:
      required: true
  - type: dropdown
    id: sponsorship
    attributes:
      label: Does this internship offer sponsorship?
      description: |
        If the posting does not specify, or it does not fall into one of these
        categories, select "Other" then specify in parentheses at the end of
        the Internship Title what the sponsorship status is
      multiple: false
      options:
        - Offers Sponsorship
        - Does Not Offer Sponsorship
        - U.S. Citizenship is Required
        - Other
    validations:
      required: true
  - type: dropdown
    id: active
    attributes:
      label: Is this internship currently accepting applications?
      multiple: false
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email associated with your GitHub account (Optional)
      description: |
        If you would like to be listed as the contributor to the repository when our github action 
        commits your contribution to the repo, please provide your email. This is the only time your 
        email will be used. If left blank, your contribution will still be made, but it will be made 
        by the bot actions@github.com.
      placeholder: ex. firstLast@gmail.com
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: Extra Notes (Optional)
      description: |
        Optionally, you may provide extra context/insights to our team about the internship.
        This will not be shown anywhere on the repo, but might ensure your contribution is accepted.
      placeholder: This is an exciting new company in the vr space...
    validations:
      required: false
